pipeline {
    options {
        timestamps()
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    agent {
        node { label 'translator && aws && build && sri' }
    }
    parameters {
        string(name: 'BUILD_VERSION', defaultValue: '', description: 'The build version to deploy (optional)')
        choice(name: 'LOAD_DATA', choices: 'no\nyes', description: 'Load data or not, default no')
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region to deploy')
        string(name: 'KUBERNETES_CLUSTER_NAME', defaultValue: 'translator-eks-ci-blue-cluster', description: 'AWS EKS that will host this application')
    }
    triggers {
        pollSCM('H/2 * * * *')
    }
    environment {
        DEPLOY_ENV = "ci"
    }
    stages {
        stage('Clean') {
            steps {
                cleanWs()
                checkout scm
            }
        }
        stage('Build Version') {
            when {
                allOf {
                    expression {
                        return !params.BUILD_VERSION
                    }
                    anyOf {
                        changeset "helm/ontology-kp/*"
                        triggeredBy 'UserIdCause'
                    }
                }
            }
            steps{
                script {
                    def image_meta = readYaml file: 'helm/ontology-kp/ncats-images-meta.yaml'
                    env.ORIGINAL_REPO = image_meta.ontologyKpApi.image
                    env.BUILD_VERSION = image_meta.ontologyKpApi.version
                    env.ORIGINAL_REPO_BGINIT = image_meta.blazeGraphInit.image
                    env.BUILD_VERSION_BGINIT = image_meta.blazeGraphInit.version
                    env.ORIGINAL_REPO_BG = image_meta.blazeGraph.image
                    env.BUILD_VERSION_BG = image_meta.blazeGraph.version
                    currentBuild.displayName = image_meta.ontologyKpApi.version + "#" + image_meta.blazeGraphInit.version + "#" + image_meta.blazeGraph.version
                }
           }
        }
        stage('build') {
            when {
                allOf {
                    expression {
                        return !params.BUILD_VERSION
                    }
                    anyOf {
                        changeset "helm/ontology-kp/*"
                        triggeredBy 'UserIdCause'
                    }
                }
            }
            steps {
                withEnv([
                    "IMAGE_NAME=853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-ontology-kp",
                    "BUILD_VERSION=" +  (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[0] : env.BUILD_VERSION)
                ]) {
                    dir("helm/ontology-kp") {
                        script {
                            sh '''
                            docker pull $ORIGINAL_REPO:$BUILD_VERSION
                            docker tag $ORIGINAL_REPO:$BUILD_VERSION $IMAGE_NAME
                            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 853771734544.dkr.ecr.us-east-1.amazonaws.com
                            '''
                            docker.image(env.IMAGE_NAME).push("${BUILD_VERSION}")
                        }
                    }
                }
                withEnv([
                    "IMAGE_NAME=853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-odklite",
                    "BUILD_VERSION_BGINIT=" +  (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[1] : env.BUILD_VERSION_BGINIT)
                ]) {
                    dir("helm/ontology-kp") {
                        script {
                            sh '''
                            docker pull $ORIGINAL_REPO_BGINIT:$BUILD_VERSION_BGINIT
                            docker tag $ORIGINAL_REPO_BGINIT:$BUILD_VERSION_BGINIT $IMAGE_NAME
                            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 853771734544.dkr.ecr.us-east-1.amazonaws.com
                            '''
                            docker.image(env.IMAGE_NAME).push("${BUILD_VERSION}")
                        }
                    }
                }
                withEnv([
                    "IMAGE_NAME=853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-blazegraph",
                    "BUILD_VERSION_BG=" +  (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[2] : env.BUILD_VERSION_BG)
                ]) {
                    dir("helm/ontology-kp") {
                        script {
                            sh '''
                            docker pull $ORIGINAL_REPO_BG:$BUILD_VERSION_BG
                            docker tag $ORIGINAL_REPO_BG:$BUILD_VERSION_BG $IMAGE_NAME
                            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 853771734544.dkr.ecr.us-east-1.amazonaws.com
                            '''
                            docker.image(env.IMAGE_NAME).push("${BUILD_VERSION}")
                        }
                    }
                }
            }
        }
        stage('Deploy') {
            agent {
                label 'translator && ci && deploy'
            }
            when {
                anyOf {
                    changeset "helm/ontology-kp/*"
                    triggeredBy 'UserIdCause'
                }
            }
            environment {
              APP = "ontology-kp"
            }
            steps {
                checkout scm
                dir("helm/ontology-kp") {
                    configFileProvider([
                        configFile(fileId: 'prepare.sh', targetLocation: 'prepare.sh')
                    ]){    
                        sh '''
                            aws --region ${AWS_REGION} eks update-kubeconfig --name ${KUBERNETES_CLUSTER_NAME}
                            /bin/bash prepare.sh
                            mv ncats-dev-values.yaml ./values-ncats.yaml
                            /bin/bash deploy.sh
                            '''
                    }
                }
            }
            post {
                always {
                    echo " Clean up the workspace in deploy node!"
                    cleanWs()
                }
            }
        }
    }
}
