apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-qgraph-svc
  labels:
    {{- include "qgraph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.qgraph.service.type }}
  ports:
    - port: {{ .Values.qgraph.service.port }}
      targetPort: {{ .Values.qgraph.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "qgraph.selectorLabels" . | nindent 4 }}
    service-type: webserver
---
{{ if .Values.robokache.enabled }}
  apiVersion: v1
  kind: Service
  metadata:
    name: robokache-svc
    labels:
      {{- include "qgraph.labels" . | nindent 4 }}
      service-type: database
  spec:
    type: {{ .Values.robokache.service.type }}
    ports:
      - port: {{ .Values.robokache.service.port }}
        targetPort: 8080
        protocol: TCP
        name: robokache-port
    selector:
      {{- include "qgraph.selectorLabels" . | nindent 4 }}
      service-type: database
{{ end }}
