# Default values for test-harness.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

test_harness:
  tag: latest
  pullPolicy: Always
  repository: ghcr.io/translatorsri/testharness
  cronInterval: fillthisin
  access_token: fillthisin
  reporter_url: fillthisin
  tests_url: fillthisin
  test_suite: fillthisin
  
resources:
  limits:
    cpu: 1000m
    memory: 10Gi
  requests:
    cpu: 800m
    memory: 8Gi

securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
