apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "robokop-ui-v2.fullname" . }}-neo4j
  labels:
    {{- include "robokop-ui-v2.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "robokop-ui-v2.fullname" . }}-neo4j-service
  selector:
    matchLabels:
      {{- include "robokop-ui-v2.selectorLabels" . | nindent 6 }}
      app-name: neo4j
  template:
    metadata:
      labels:
        {{- include "robokop-ui-v2.selectorLabels" . | nindent 8 }}
        app-name: neo4j
    spec:
      {{- if .Values.neo4j.dataUrl }}
      initContainers:
        - name: {{ include "robokop-ui-v2.fullname" . }}-neo4j-download-container
          image: {{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag }}
          command:
            - '/download_data.sh'
          env:
            - name: NEO4J_DATA_URL
              value: {{ .Values.neo4j.dataUrl }}
          resources:
            {{- toYaml .Values.neo4j.initresources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: {{ include "robokop-ui-v2.fullname" . }}-neo4jkp-pvc
              subPath: neo4j_data
            - name: {{ include "robokop-ui-v2.fullname" . }}-scripts
              mountPath: /download_data.sh
              subPath: download_data.sh
        - name: {{ include "robokop-ui-v2.fullname" . }}-neo4j-seed-container
          image: {{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag }}
          command:
            - '/seed_db.sh'
          volumeMounts:
            - mountPath: /data
              name: {{ include "robokop-ui-v2.fullname" . }}-neo4jkp-pvc
              subPath: neo4j_data
            - name: {{ include "robokop-ui-v2.fullname" . }}-scripts
              mountPath: /seed_db.sh
              subPath: seed_db.sh
      {{- end }}
      containers:
        - image: {{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag }}
          name: {{ include "robokop-ui-v2.fullname" . }}-neo4j-container
          imagePullPolicy:  {{ .Values.neo4j.imagePullPolicy }}
          env:
          - name: JAVA_HOME
            value: /usr/lib/jvm/java-11-openjdk/jre
          - name: NEO4J_AUTH
            value: "{{ .Values.neo4j.username }}/{{ .Values.neo4j.password }}"
          - name: NEO4J_dbms_connectors_default__listen__address
            value: "0.0.0.0"
          - name: NEO4J_dbms_memory_heap_initial__size
            value: "{{ .Values.neo4j.heapSize }}"
          - name: NEO4J_dbms_memory_heap_max__size
            value: "{{ .Values.neo4j.heapSize }}"
          - name: NEO4J_dbms_memory_pagecache_size
            value: "{{ .Values.neo4j.pageCacheSize }}"
          - name: NEO4J_dbms_read__only
            value: "{{ .Values.neo4j.readOnly }}"
          - name: NEO4J_dbms_security_procedures_unrestricted
            value: "apoc.*"
          - name: NEO4J_dbms_jvm_additional
            value: "-XX:+UnlockExperimentalVMOptions -XX:+UseZGC"
          ports:
            - name: neo4j-http
              containerPort: 7474
              protocol: TCP
            - name: neo4j-https
              containerPort: 7473
              protocol: TCP
            - name: neo4j-bolt
              containerPort: 7687
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /db/data/labels
              port: neo4j-http
              httpHeaders:
                - name: Authorization
                  value: "Basic {{ printf "neo4j:%s" .Values.neo4j.password | b64enc }}"
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /db/data/labels
              port: neo4j-http
              httpHeaders:
                - name: Authorization
                  value: "Basic {{ printf "%s:%s" .Values.neo4j.username .Values.neo4j.password | b64enc }}"
            initialDelaySeconds: 60
          resources:
            requests:
              memory: {{ .Values.neo4j.totalMemory }}
            limits:
              memory: {{ .Values.neo4j.totalMemory }}
          volumeMounts:
          - mountPath: /data
            name: {{ include "robokop-ui-v2.fullname" . }}-neo4jkp-pvc
            subPath: neo4j_data
          - mountPath: /logs
            name: {{ include "robokop-ui-v2.fullname" . }}-neo4jkp-pvc
            subPath: neo4j_logs
      restartPolicy: Always
      volumes:
        - name: {{ include "robokop-ui-v2.fullname" . }}-scripts
          configMap:
            name: {{ include "robokop-ui-v2.fullname" . }}-configmap
            defaultMode: 0777
  volumeClaimTemplates:
    - metadata:
        name: {{ include "robokop-ui-v2.fullname" . }}-neo4jkp-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.neo4j.storageSize }}
