{{ if or .Values.dataUrl .Values.forceRun }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "name-lookup.fullname" . }}-restore-job
spec:
  template:
    metadata:
      name: "{{- include "name-lookup.fullname" . }}-restore-job"
    spec:
      volumes:
        - name: {{ include "name-lookup.fullname" . }}-configmap
          configMap:
            name: {{ include "name-lookup.fullname" . }}-configmap
            defaultMode: 0777
      restartPolicy: OnFailure
      containers:
        - name: restore-container
          image: "{{ .Values.busybox.image.repository }}:{{ .Values.busybox.image.tag }}"
          command:
            - /restore.sh
          stdin: true
          tty: true
          volumeMounts:
            - mountPath:  /restore.sh
              name: {{ include "name-lookup.fullname" . }}-configmap
              subPath: "restore.sh"
{{ end }}