{{ if or .Values.dataUrl .Values.forceRun }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "name-lookup.fullname" . }}-restore-job
spec:
  template:
    metadata:
      name: "{{- include "name-lookup.fullname" . }}-restore-job"
    spec:
      volumes:
        - name: {{ include "name-lookup.fullname" . }}-configmap
          configMap:
            name: {{ include "name-lookup.fullname" . }}-configmap
            defaultMode: 0777
        {{ if and .Values.blocklist.url .Values.blocklist.storage }}
        - name: {{ include "name-lookup.fullname" . }}-blocklist
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: [ "ReadWriteOnce" ]
                resources:
                  requests:
                    storage: {{ .Values.blocklist.storage }}
        {{ end }}
      restartPolicy: OnFailure
      containers:
        - name: restore-container
          image: "{{ .Values.busybox.image.repository }}:{{ .Values.busybox.image.tag }}"
          command:
            - /restore.sh
          stdin: true
          tty: true
          env:
          {{ if and .Values.blocklist.url .Values.blocklist.secrets.github_personal_access_token }}
          - name: GITHUB_PERSONAL_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "name-lookup.fullname" . }}-secrets
                key: github_personal_access_token
                optional: false
          {{ end }}
          volumeMounts:
            - mountPath: /restore.sh
              name: {{ include "name-lookup.fullname" . }}-configmap
              subPath: "restore.sh"
            {{ if and .Values.blocklist.url .Values.blocklist.storage }}
            - mountPath: /var/blocklist
              name: {{ include "name-lookup.fullname" . }}-blocklist
            {{ end }}
{{ end }}
