{{ if .Values.blocklist.secrets.github_personal_access_token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name-lookup.fullname" . }}-secrets
  labels:
    {{- include "name-lookup.labels" . | nindent 4 }}
type: Opaque
stringData:
  github_personal_access_token: {{ .Values.blocklist.secrets.github_personal_access_token }}
{{ end }}
