app:
  neo4j:
    dataUrl: https://stars.renci.org/var/plater/graphs/HMDB_Automat/1ffe388752ed4727/neo4j.dump
  memgraph:
    dataUrl: https://stars.renci.org/var/plater/graphs/HMDB_Automat/1ffe388752ed4727/memgraph.cypher
graphMetadataUrl: https://stars.renci.org/var/plater/graphs/HMDB_Automat/1ffe388752ed4727/graph-metadata.json
schemaUrl: https://stars.renci.org/var/plater/graphs/HMDB_Automat/1ffe388752ed4727/schema.json
metadataUrl: https://stars.renci.org/var/plater/graphs/HMDB_Automat/1ffe388752ed4727/HMDB_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/graphs/HMDB_Automat/1ffe388752ed4727/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/graphs/HMDB_Automat/1ffe388752ed4727/testing_data.json
