apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "node-normalization-webserver.fullname" . }}-webserver-config"
data:
  redis_config.yaml: |
    {{ .Values.redis_backend_config | toYaml | nindent 4 }}
