apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-normalization-webserver.fullname" . }}-service-sub-path-trapi1-2
  labels:
    {{- include "node-normalization-webserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
      name: web-port
  selector:
    {{- include "node-normalization-webserver.selectorLabels" . | nindent 4 }}
    service-type: "webserver"
    path: "1.2"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-normalization-webserver.fullname" . }}-service-root
  labels:
    {{- include "node-normalization-webserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
      name: web-port
  selector:
    {{- include "node-normalization-webserver.selectorLabels" . | nindent 4 }}
    service-type: "webserver"
    path: "root"