apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-normalization-webserver.fullname" . }}-web-service-sub-path
  labels:
    {{- include "node-normalization-webserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
      name: web-port
  selector:
    app: "{{- include "node-normalization-webserver.name" . }}"
    service-type: "webserver"
    path: "1.1"

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-normalization-webserver.fullname" . }}-web-service-root
  labels:
    {{- include "node-normalization-webserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
      name: web-port
  selector:
    app: "{{- include "node-normalization-webserver.name" . }}"
    service-type: "webserver"
    path: "root"