image:
  repository: 853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-aragorn-ranker
  tag: DOCKER_IMAGE_VERSION

# no values
ingress:
  enabled: true
  host: "aragorn-ranker.transltr.io"
  class: ""
  annotations: {}

web:
  serverHostName: https://aragorn-ranker.transltr.io

# Use OMNICORP secrets in values-populated.yaml


answercoalesce:
 # Assumes ac is deployed in the same namespace
  fullServiceName: answer-coalesce-redis-service
  redisServicePort: 6379

x_trapi:
  maturity:
    value: "prod"
  location:
    value: "ITRB"
