app:
  neo4j:
    dataUrl: https://stars.renci.org/var/plater/graphs/STRING-DB_Automat/6a5d9e79a31500ec/neo4j.dump
  memgraph:
    dataUrl: https://stars.renci.org/var/plater/graphs/STRING-DB_Automat/6a5d9e79a31500ec/memgraph.cypher
graphMetadataUrl: https://stars.renci.org/var/plater/graphs/STRING-DB_Automat/6a5d9e79a31500ec/graph-metadata.json
schemaUrl: https://stars.renci.org/var/plater/graphs/STRING-DB_Automat/6a5d9e79a31500ec/schema.json
metadataUrl: https://stars.renci.org/var/plater/graphs/STRING-DB_Automat/6a5d9e79a31500ec/STRING-DB_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/graphs/STRING-DB_Automat/6a5d9e79a31500ec/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/graphs/STRING-DB_Automat/6a5d9e79a31500ec/testing_data.json
