app:
  neo4j:
    dataUrl: https://stars.renci.org/var/plater/graphs/HGNC_Automat/18d7d0e936fac5fe/neo4j.dump
  memgraph:
    dataUrl: https://stars.renci.org/var/plater/graphs/HGNC_Automat/18d7d0e936fac5fe/memgraph.cypher
graphMetadataUrl: https://stars.renci.org/var/plater/graphs/HGNC_Automat/18d7d0e936fac5fe/graph-metadata.json
schemaUrl: https://stars.renci.org/var/plater/graphs/HGNC_Automat/18d7d0e936fac5fe/schema.json
metadataUrl: https://stars.renci.org/var/plater/graphs/HGNC_Automat/18d7d0e936fac5fe/HGNC_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/graphs/HGNC_Automat/18d7d0e936fac5fe/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/graphs/HGNC_Automat/18d7d0e936fac5fe/testing_data.json
