ingress:
  host: robokop.renci.org
  public: true
  paths:
  - path: /api-docs(?:\/|$)(.*)
    name: api-docs-svc
    port: 8080
  - path: /question-builder(?:\/|$)(.*)
    name: qgraph-svc
    port: 7080
  - path: /(.*)$
    name: landing-page-svc
    port: 3000

# qgraph .Values override
qgraph:
  env:
    # robokache: http://qgraph-robokache
    strider: https://strider.renci.org/1.3
    aragorn: http://aragorn-aragorn-service:8080
    robokop_ara: http://aragorn-aragorn-robokop-service:8080
    node_normalizer: http://nn-web-node-normalization-web-service-root.translator-dev:8080
    name_resolver: https://robokop-name-resolver.apps.renci.org
    biolink: https://raw.githubusercontent.com/biolink/biolink-model/v3.5.4/biolink-model.yaml

  qgraph:
    repository: ghcr.io/robokopu24/qgraph
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.3.0"
    service:
      type: ClusterIP
      port: 7080

  robokache:
    repository: ghcr.io/ncats-gamma/robokache
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v4.1.5"
    service:
      type: ClusterIP
      port: 8080
    dbPath: "/data"
