dataUrl: https://stars.renci.org/var/plater/bl-4.2.0/CTD_Automat/8b5f74462c4179ca/graph_8b5f74462c4179ca.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-4.2.0/CTD_Automat/8b5f74462c4179ca/CTD_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-4.2.0/CTD_Automat/8b5f74462c4179ca/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-4.2.0/CTD_Automat/8b5f74462c4179ca/testing_data.json