# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

# this docker file creates the db-backup-job image

# start with the latest debian image
FROM debian:stable-slim

# get some credit
LABEL maintainer="Phil Owen (powen@renci.org)"

# update the image base
RUN apt-get update && apt-get -y upgrade

# install postgre
RUN apt -y install postgresql

# install an editor
RUN apt -y install nano