dataUrl: https://stars.renci.org/var/plater/bl-4.2.1/COHD_Automat/8ebe848c557cff42/neo4j.dump
metadataUrl: https://stars.renci.org/var/plater/bl-4.2.1/COHD_Automat/8ebe848c557cff42/COHD_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-4.2.1/COHD_Automat/8ebe848c557cff42/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-4.2.1/COHD_Automat/8ebe848c557cff42/testing_data.json