# Default values for robokop-ui-v2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
frontend:
  image:
    repository: ghcr.io/ncats-gamma/robokop-rewrite/frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80


queryDispatcher:
  image:
    repository: ghcr.io/ncats-gamma/robokop-rewrite/query-dispatcher
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

robokache:
  image:
    repository: ghcr.io/ncats-gamma/robokache
    tag: v4.1.4
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  storageSize: 50Gi
  dataDir: /app/data

proxy:
  image:
    repository: ghcr.io/ncats-gamma/robokop-rewrite/proxy
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

neo4j:
  image:
    repository: renciorg/neo4jkp
    tag: latest
  imagePullPolicy: Always
  username: neo4j
  password: "ncatsgamma"
  initresources:
    requests:
      memory: 5Gi
      cpu: 1000m
    limits:
      memory: 10Gi
      cpu: 500m
  heapSize: 32G
  pageCacheSize: 10G
  totalMemory: 45G
  readOnly: false
  dataUrl: https://robokopkg.renci.org/baseline_plus_genetics_9-2-2020.db.dump
  storageSize: 200G #
  service:
    type: ClusterIP
    httpPort: 7474
    boltPort: 7687
    httpsPort: 7473

messenger:
  image:
    repository: renciorg/robokop_messenger
    tag: "2.0"
  cacheHost: "omnicorp-cache.edc.renci.org"
  cachePort: "6380"
  cachePassword: "stayoutoftrouble"
  omnicorpUser: "murphy"
  omnicorpPassword: "ncatsgamma"
  omnicorpHost: "omnicorp.edc.renci.org"
  omnicorpDB: "robokop"
  omnicorpPort: "5432"
  service:
    type: ClusterIP
    port: 80


env:
  messengerHost: http://robokop-messenger-service:4868


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: translator
    ginx.ingress.kubernetes.io/proxy-body-size: 250m
  host: robokop.renci.org


