apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "biolink-lookup.fullname" . }}
  labels:
    {{- include "biolink-lookup.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "biolink-lookup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "biolink-lookup.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8144
              protocol: TCP
          env:
          - name: DEFAULT_VERSION
            value: {{ .Values.app.defaultVersion }}
          - name: SERVER_ROOT
            value: {{ .Values.web }}
