# Default values for icees-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: renci/icees-api-server
  pullPolicy: Always
  tag: "0.5.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podSecurityContext: {}
  # fsGroup: 2000

service:
  type: ClusterIP
  port: 8080
  resources:
    requests:
      cpu: "2"
      memory: 8Gi
    limits:
      memory: "10Gi"
      cpu: "4"

redis:
  port: "6379"
  image:
    repository: redis
    tag: "6.2"
  storage:
    size: 10Gi 

secrets:
  ICEES_HOST: ##############
  ICEES_DBUSER: ##############
  ICEES_DBPASS: ##############
  POSTGRES_PASSWORD: ##############
  ICEES_DATABASE: ##############

custom_envs:
  INSTANCE_NAME: ##############

server_env_config:
  UID: "1001"
  GID: "1001"
  ICEES_PORT: "5432"
  ICEES_API_LOG_PATH: ##############
  ICEES_API_HOST_PORT: 8080
  OPENAPI_TITLE: ##############
  POOL_SIZE: "10"
  MAX_OVERFLOW: "0"
  OPENAPI_SCHEME: "https"
  DATA_PATH: "./db/data"
  DB_PATH: ##############
  CONFIG_PATH: ##############
  ICEES_API_INSTANCE_NAME: ##############
  ICEES_INFORES_CURIE: ##############
  OPENAPI_SERVER_MATURITY: ##############
  OPENAPI_SERVER_LOCATION: "RENCI"

ingress:
  host: ##############
  class: ""
  pathType: Prefix
  annotations:
    # kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 256m 
