apiVersion: v1
kind: Service
metadata:
  name: {{ include "cam-pipeline-web-server.fullname" . }}-web-service
  labels:
    app.kubernetes.io/name: cam-pipeline-web-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "cam-pipeline-web-server.name" . }}
    service-type: "webserver"