apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graph-registry.fullname" . }}
  labels:
    {{- include "graph-registry.labels" . | nindent 4 }}
type: Opaque
data:
  refresh-password: {{ .Values.app.refreshPassword | b64enc | quote }}
