dataUrl: https://stars.renci.org/var/plater/graphs/RobokopKG/6fe13d850fdbf89c/graph_6fe13d850fdbf89c.db.dump
metadataUrl: https://stars.renci.org/var/plater/graphs/RobokopKG/6fe13d850fdbf89c/RobokopKG.meta.json
metaKGUrl: https://stars.renci.org/var/plater/graphs/RobokopKG/6fe13d850fdbf89c/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/graphs/RobokopKG/6fe13d850fdbf89c/testing_data.json