app:
  neo4j:
    dataUrl: https://stars.renci.org/var/plater/graphs/OHD_Carolina_Automat/c157584568c21397/neo4j.dump
  memgraph:
    dataUrl: https://stars.renci.org/var/plater/graphs/OHD_Carolina_Automat/c157584568c21397/memgraph.cypher
graphMetadataUrl: https://stars.renci.org/var/plater/graphs/OHD_Carolina_Automat/c157584568c21397/graph-metadata.json
schemaUrl: https://stars.renci.org/var/plater/graphs/OHD_Carolina_Automat/c157584568c21397/schema.json
metadataUrl: https://stars.renci.org/var/plater/graphs/OHD_Carolina_Automat/c157584568c21397/OHD_Carolina_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/graphs/OHD_Carolina_Automat/c157584568c21397/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/graphs/OHD_Carolina_Automat/c157584568c21397/testing_data.json
