apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filter_results_top_n.fullname" . }}
  labels:
    app: {{ include "filter_results_top_n.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "filter_results_top_n.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "filter_results_top_n.name" . }}
    spec:
      containers:
      - env:
        - name: WEB_HOST
          value: 0.0.0.0
        - name: WEB_PORT
          value: {{ .Values.app.port | quote}}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: {{ .Chart.Name }}-web-container
        ports:
        - containerPort: {{ .Values.app.port }}
          name: http
          protocol: TCP
      restartPolicy: Always
