apiVersion: v1
kind: Service
metadata:
  name: {{ include "filter-results-top-n.fullname" . }}-web-service
  labels:
    {{- include "filter-results-top-n.labels" . | nindent 4 }}
spec:
  {{- include "filter-results-top-n.serviceDefinition" . | nindent 2}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port}}
      protocol: TCP
      name: http
  selector:
    app: {{ include "filter-results-top-n.name" . }}
