apiVersion: v1
kind: Service
metadata:
  name: {{ include "filter_results_top_n.fullname" . }}-web-service
  labels:
    {{- include "filter_results_top_n.labels" . | nindent 4 }}
spec:
  {{- include "filter_results_top_n.serviceDefinition" . | nindent 2}}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port}}
      protocol: TCP
      name: http
  selector:
    app: {{ include "filter_results_top_n.name" . }}
