# Default values for ontology-tools.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository:
  tag: latest
  # Valid image names are  renciorg/green-onto_gunicorn and renciorg/green-bionames

nameOverride: ""
fullnameOverride: ""

uberongraphEndpoint: "https://ubergraph.apps.renci.org/sparql"
HTTPS_PROXY: "http://proxy.renci.org:8080"

service:
  type: ClusterIP
  port: 80

ingress:
  pathType: ImplementationSpecific
  host:
  class:
  tls:
    enabled: False