app:
  neo4j:
    dataUrl: https://stars.renci.org/var/plater/graphs/DrugCentral_Automat/4d492047aa51f86f/neo4j.dump
  memgraph:
    dataUrl: https://stars.renci.org/var/plater/graphs/DrugCentral_Automat/4d492047aa51f86f/memgraph.cypher
graphMetadataUrl: https://stars.renci.org/var/plater/graphs/DrugCentral_Automat/4d492047aa51f86f/graph-metadata.json
schemaUrl: https://stars.renci.org/var/plater/graphs/DrugCentral_Automat/4d492047aa51f86f/schema.json
metadataUrl: https://stars.renci.org/var/plater/graphs/DrugCentral_Automat/4d492047aa51f86f/DrugCentral_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/graphs/DrugCentral_Automat/4d492047aa51f86f/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/graphs/DrugCentral_Automat/4d492047aa51f86f/testing_data.json
