dataUrl: https://stars.renci.org/var/plater/bl-4.2.0/DrugCentral_Automat/69dab8a3d7bce2f4/graph_69dab8a3d7bce2f4.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-4.2.0/DrugCentral_Automat/69dab8a3d7bce2f4/DrugCentral_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-4.2.0/DrugCentral_Automat/69dab8a3d7bce2f4/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-4.2.0/DrugCentral_Automat/69dab8a3d7bce2f4/testing_data.json