apiVersion: v1
kind: Service
metadata:
  name: annotation-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: annotation-backend
  ports:
  - protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: 8000
  type: {{ .Values.backend.service.type }}