apiVersion: apps/v1
kind: Deployment
metadata:
  name: annotation-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: annotation-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: annotation-frontend
  template:
    metadata:
      labels:
        app: annotation-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}