apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "cam-pipeline-builder.fullname" . }}-data-pvc"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data.storageSize }}