apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- include "cam-pipeline-builder.fullname" . }}-loader-config"
data:
  run.sh: |-
    #!/bin/bash
    cd /opt/docker && make all && cp cam-db-reasoned.jnl /data

