apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ include "robokop.fullname" . }}-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.logs.storageSize }}