apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "robokop.fullname" . }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.manager.postgres.storageSize }}