apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "node-normalization-loader.fullname" . }}-conflation-pvc"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "node-normalization-loader.fullname" . }}-compendia-pvc"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.data.storageSize }}