{{- $fullName := include "node-normalization-loader.fullname" . -}}
{{- $compendiaStorageSize := .Values.data.compendia.storageSize }}
{{- $conflationStorageSize := .Values.data.conflations.storageSize }}
{{- range $index, $compendia := .Values.data.compendia.files }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $fullName }}-compendia-{{ $index }}-pvc"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $compendiaStorageSize }}
---
{{- end }}
---
{{- range $index, $compendia := .Values.data.conflations.configs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ $fullName}}-conflation-{{ $index }}-pvc"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ $conflationStorageSize }}
---
{{- end }}