apiVersion: batch/v1
kind: Job
metadata:
  name: "{{- include "node-normalization-loader.fullname" . }}-com-job"
spec:
  template:
    metadata:
      name: "{{- include "node-normalization-loader.fullname" . }}-com-job"
    spec:
      containers:
        - name: loader-container
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /code/run_loader.sh
          volumeMounts:
            - mountPath:  /code/run_loader.sh
              name: "loader-config"
              subPath: "run_loader_compendia.sh"
            - mountPath: /data
              name: "data-dir"
            - mountPath: /code/redis_config.yaml
              name: "loader-config"
              subPath: "redis_config.yaml"
            - mountPath: /code/config.json
              name: "loader-config"
              subPath: "config-compendia.json"
          resources:
            {{ .Values.resources | toYaml | nindent 12 }}
      restartPolicy: OnFailure

      volumes:
        - name: loader-config
          configMap:
            name: "{{ include "node-normalization-loader.fullname" . }}-loader-config"
            defaultMode: 0777
        - name: data-dir
          persistentVolumeClaim:
            claimName: "{{ include "node-normalization-loader.fullname" . }}-compendia-pvc"
---
{{- if .Values.data.conflations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{- include "node-normalization-loader.fullname" . }}-con-job"
spec:
  template:
    metadata:
      name: "{{- include "node-normalization-loader.fullname" . }}-con-job"
    spec:
      containers:
        - name: loader-container
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /code/run_loader.sh
          volumeMounts:
            - mountPath:  /code/run_loader.sh
              name: "loader-config"
              subPath: "run_loader_conflation.sh"
            - mountPath: /data
              name: "data-dir"
            - mountPath: /code/redis_config.yaml
              name: "loader-config"
              subPath: "redis_config.yaml"
            - mountPath: /code/config.json
              name: "loader-config"
              subPath: "config-conflation.json"
          resources:
            {{ .Values.resources | toYaml | nindent 12 }}
      restartPolicy: OnFailure
      volumes:
        - name: loader-config
          configMap:
            name: "{{ include "node-normalization-loader.fullname" . }}-loader-config"
            defaultMode: 0777
        - name: data-dir
          persistentVolumeClaim:
            claimName: "{{ include "node-normalization-loader.fullname" . }}-conflation-pvc"
{{- end -}}