apiVersion: batch/v1
kind: Job
metadata:
  name: "{{- include "node-normalization-loader.fullname" . }}-job"
spec:
  template:
    metadata:
      name: "{{- include "node-normalization-loader.fullname" . }}-job"
    spec:
      containers:
        - name: loader-container
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /home/murphy/run_loader.sh
          volumeMounts:
            - mountPath:  /home/murphy/run_loader.sh
              name: "loader-config"
              subPath: "run_loader.sh"
            - mountPath: /data
              name: "data-dir"
            - mountPath: /home/murphy/redis_config.yaml
              name: "loader-config"
              subPath: "redis_config.yaml"
            - mountPath: /home/murphy/config.json
              name: "loader-config"
              subPath: "config.json"
          resources:
            {{ .Values.resources | toYaml | nindent 12 }}
      restartPolicy: OnFailure

      volumes:
        - name: loader-config
          configMap:
            name: "{{ include "node-normalization-loader.fullname" . }}-loader-config"
            defaultMode: 0777
        - name: data-dir
          persistentVolumeClaim:
            claimName: "{{ include "node-normalization-loader.fullname" . }}-data-pvc"