apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plater-graphs-server.fullname" . }}-nginx-config
  labels:
    {{- include "plater-graphs-server.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    server {
      listen {{ .Values.service.containerPort }};

      root {{ .Values.nfs.mountPath }};

      index index.html index.htm;

      location / {
        try_files $uri $uri/ =404;
        autoindex off;
      }
    }
