apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shepherd.fullname" . }}-configmap
data:
  SERVER_URL: "https://{{ .Values.ingress.host }}"
  SERVER_MATURITY: {{ .Values.x_trapi.maturity }}
  SERVER_LOCATION: {{ .Values.x_trapi.location }}

  LOG_LEVEL: {{ .Values.shepherd.log_level }}

  POSTGRES_USER: postgres
  POSTGRES_HOST: shepherd-db
  POSTGRES_PORT: "{{ .Values.shepherd_db.service.port }}"
  POSTGRES_PASSWORD: {{ .Values.shepherd_db.auth.password }}

  REDIS_HOST: shepherd-broker
  REDIS_PORT: "{{ .Values.shepherd_broker.service.port }}"
  REDIS_PASSWORD: {{ .Values.shepherd_broker.auth.password }}

  LOOKUP_TIMEOUT: "{{ .Values.shepherd.lookup_timeout }}"
  CALLBACK_HOST: "https://{{ .Values.ingress.host }}"
  KG_RETRIEVAL_URL: {{ .Values.shepherd.kg_retrieval_url }}
  SYNC_KG_RETRIEVAL_URL: {{ .Values.shepherd.sync_kg_retrieval_url }}
  KG_REHYDRATE_URL: {{ .Values.shepherd.kg_rehydrate_url }}
  DEFAULT_DATA_TIER: "{{ .Values.shepherd.default_data_tier }}"
  OMNICORP_URL: {{ .Values.shepherd.omnicorp_url }}
  ARAX_URL: {{ .Values.shepherd.arax_url }}
  NODE_NORM: {{ .Values.shepherd.node_norm }}

  # OTEL_ENABLED: "True"
  JAEGER_HOST: {{ .Values.otel.jaeger_host }}
  JAEGER_PORT: "{{ .Values.otel.jaeger_port }}"

  GANDALF_GRAPH_PATH: {{ .Values.gandalf.sharedData.mountPath }}

  OMNICORP_CURIES_LMDB_PATH: "{{ .Values.omnicorpLoader.sharedData.mountPath }}/curies.lmdb"
  OMNICORP_SHARED_COUNTS_LMDB_PATH: "{{ .Values.omnicorpLoader.sharedData.mountPath }}/shared_counts.lmdb"
  # REDIS_TTL: {{ .Values.shepherd.redis_ttl }}
