apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shepherd.fullname" . }}-gandalf-data
  labels:
    {{- include "shepherd.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- if .Values.gandalfLoader.enabled }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.gandalf.persistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.gandalf.persistentVolume.size }}
