apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shepherd.fullname" . }}-merge-message
  labels:
    {{- include "shepherd.labels" . | nindent 4 }}
    service-type: worker
spec:
  replicas: {{ .Values.merge_message.replicaCount }}
  {{ if .Values.merge_message.strategy }}
  strategy:
    type: {{ .Values.merge_message.strategy }}
  {{ end }}
  selector:
    matchLabels:
      {{- include "shepherd.selectorLabels" . | nindent 6 }}
      service-type: worker
  template:
    metadata:
      labels:
        {{- include "shepherd.selectorLabels" . | nindent 8 }}
        service-type: worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") .  | sha256sum }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{ . | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-merge-message
          image: "{{ .Values.merge_message.image.repository }}:{{ .Values.shepherd.tag }}"
          imagePullPolicy: "{{ .Values.merge_message.image.imagePullPolicy }}"
          envFrom:
            - configMapRef:
                name: {{ include "shepherd.fullname" . }}-configmap
          command:
            - 'python'
          args:
            - "worker.py"
          {{ if .Values.merge_message.resources }}
          resources: {{ toYaml .Values.merge_message.resources | nindent 12 }}
          {{ end }}
          volumeMounts:
          - name: {{ include "shepherd.fullname" . }}-logs-pvc
            mountPath: /app/logs/
      volumes:
      - name: {{ include "shepherd.fullname" . }}-logs-pvc
        persistentVolumeClaim:
          claimName: {{ include "shepherd.fullname" . }}-logs-pvc
      {{- with .Values.shepherd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shepherd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shepherd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
