{{- if and (eq .Values.graph.backend "gandalf") (not .Values.graph.external) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gandalf.fullname" . }}-data
  labels:
    {{- include "gandalf.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    {{- if .Values.app.gandalf.loader.enabled }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    {{- end }}
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- toYaml .Values.app.gandalf.persistentVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.app.gandalf.persistentVolume.size }}
  volumeMode: Filesystem
{{- end }}
