apiVersion: v1
kind: Service
metadata:
  name: {{ include "gandalf.fullname" . }}-service
  labels:
    {{- include "gandalf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.gandalf.service.type }}
  ports:
    - port: {{ .Values.app.gandalf.service.port }}
      targetPort: {{ .Values.app.gandalf.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "gandalf.selectorLabels" . | nindent 4 }}
