{{- if and (eq .Values.graph.backend "gandalf") (not .Values.graph.external) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plater.fullname" . }}-gandalf-service
  labels:
    {{- include "plater.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.gandalf.service.type }}
  ports:
    - port: {{ .Values.app.gandalf.service.port }}
      targetPort: {{ .Values.app.gandalf.service.port }}
      protocol: TCP
      name: gandalf-http
  selector:
    {{- include "plater.selectorLabels" . | nindent 4 }}
    service-type: gandalf-database
{{ end }}
