apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "memgraph.dumpPVCName" . }}
  labels:
    {{- include "memgraph.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.dumpPVC.accessMode | quote }}
  resources:
    requests:
      storage: {{ required "dumpPVC.size must be set (e.g. 5Gi, 10Gi)" .Values.dumpPVC.size }}
  storageClassName: {{ .Values.dumpPVC.storageClass | quote }}
