apiVersion: v1
kind: Service
metadata:
  name: {{ include "memgraph.fullname" . }}
  labels:
    {{- include "memgraph.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{ end }}
  ports:
    - name: bolt
      port: {{ .Values.service.portBolt }}
      targetPort: {{ .Values.service.portBolt }}
  selector:
    {{- include "memgraph.selectorLabels" . | nindent 4 }}

