apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
  labels:
    app.kubernetes.io/name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
    app.kubernetes.io/instance: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
    server-type: redis
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
      app.kubernetes.io/instance: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
      server-type: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
        app.kubernetes.io/instance: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
        server-type: redis
    spec:
      containers:
        - name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}-redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
           - containerPort: {{ .Values.redis.port }}
             name: redis-port
             protocol: TCP
    
          livenessProbe:
            periodSeconds: 5
            exec:
              command: ["redis-cli", "ping"]
          startupProbe:
            exec:
              command: ["redis-cli", "ping"]      
            failureThreshold: 30
            periodSeconds: 5    
          readinessProbe:
            periodSeconds: 5
            exec:
              command: ["redis-cli", "ping"]
          volumeMounts:
            - name: {{ .Values.custom_envs.INSTANCE_NAME }}-redis-data
              mountPath: /data 
          resources:
            {{- toYaml .Values.service.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: {{ .Values.custom_envs.INSTANCE_NAME }}-redis-data
          persistentVolumeClaim:
            claimName: {{ .Values.custom_envs.INSTANCE_NAME }}-redis-db-pvc
