apiVersion: v1
kind: Service
metadata:
  name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}       
  labels:
    app.kubernetes.io/name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}
    service-type: webserver
    trapi: "1.2"      
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ include "icees-api.fullname" . }}-trapi-{{ .Chart.AppVersion }}
    service-type: webserver
    trapi: "1.2"      
  type: {{ .Values.service.type }}

