apiVersion: v2
name: graph-registry
description: A FastAPI application to explore metadata for graphs ingested into Robokop.
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: hina-shah
    email: hinashah@renci.org
