apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "answer-appraiser.fullname" . }}-configmap
data:
  OPENAPI_SERVER_URL: https://{{ .Values.ingress.host }}
  OPENAPI_SERVER_MATURITY: {{ .Values.x_trapi.maturity.value }}
  OPENAPI_SERVER_LOCATION: {{ .Values.x_trapi.location.value }}
  ROOT_PATH: {{ .Values.ingress.path }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password }}
  REDIS_HOST: {{ .Values.env.redis_host }}
  REDIS_PORT: "{{ .Values.env.redis_port }}"
  TRAPI_VERSION: "{{ .Values.env.trapi_version }}"
  JAEGER_HOST: {{ .Values.env.jaeger_host }}
  JAEGER_PORT: "{{ .Values.env.jaeger_port }}"
  JAEGER_ENABLED: "{{ .Values.env.jaeger_enabled }}"
