# Default values for omnicorp-redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}


### REDIS config


redis:
  # full option here (https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml)
  architecture: standalone
  image:
    repository:  bitnami/redis
    tag: 7.4.1-debian-12-r2
  master:
    configuration: |-
      logfile "/data/strider_cache.log"
    resources:
      limits:
        cpu: 2
        memory: 50Gi
    readinessProbe:
      enabled: false
      # to make it available ASAP
      periodSeconds: 1
      # spans 25 mins (150 * 10 secs)
      failureThreshold: 1
    livenessProbe:
      # Liveliness probes can be off, since
      # With big cache data to load or sync , redis is alive but
      # responds with LOADING message. to avoid cyclic restarts
      # keeping this off
      enabled: false
#    initContainers:
#    - name: download-bckp
#      image: "busybox:1.35"
#      command:
#        - 'wget'
#      args:
#        - '-O'
#        - '/data/dump.rdb'
#        - 'https://stars.renci.org/var/omnicorp/redis/pathfinder_omnicorp_11_21_2024.rdb'
#      volumeMounts:
#      - name: redis-data
#        mountPath: '/data/'
#      resources:
#        limits:
#          cpu: 2
#          memory: 7Gi
    persistence:
      size: 30Gi
  replica:
    replicaCount: 0
  # anything that goes into redis.conf file
  commonConfiguration: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly no
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
