app:
  neo4j:
    dataUrl: https://stars.renci.org/var/plater/graphs/PHAROS_Automat/a6022ac51591a48b/neo4j.dump
  memgraph:
    dataUrl: https://stars.renci.org/var/plater/graphs/PHAROS_Automat/a6022ac51591a48b/memgraph.cypher
graphMetadataUrl: https://stars.renci.org/var/plater/graphs/PHAROS_Automat/a6022ac51591a48b/graph-metadata.json
schemaUrl: https://stars.renci.org/var/plater/graphs/PHAROS_Automat/a6022ac51591a48b/schema.json
metadataUrl: https://stars.renci.org/var/plater/graphs/PHAROS_Automat/a6022ac51591a48b/PHAROS_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/graphs/PHAROS_Automat/a6022ac51591a48b/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/graphs/PHAROS_Automat/a6022ac51591a48b/testing_data.json
