dataUrl: https://stars.renci.org/var/plater/bl-4.2.1/Hetio_Automat/85a5f53e63150e1e/graph_85a5f53e63150e1e.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-4.2.1/Hetio_Automat/85a5f53e63150e1e/Hetio_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-4.2.1/Hetio_Automat/85a5f53e63150e1e/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-4.2.1/Hetio_Automat/85a5f53e63150e1e/testing_data.json
