apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "robokopkg.fullname" . }}-neo4j
  labels:
    {{- include "robokopkg.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "robokopkg.fullname" . }}-neo4j-service
  selector:
    matchLabels:
      {{- include "robokopkg.selectorLabels" . | nindent 6 }}
      service-type: database
  template:
    metadata:
      labels:
        {{- include "robokopkg.selectorLabels" . | nindent 8 }}
        service-type: database
    spec:
      {{- if .Values.neo4j.dataUrl }}
      initContainers:
        - name: {{ include "robokopkg.fullname" . }}-neo4j-download-container
          image: {{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag }}
          command:
            - '/download_data.sh'
          env:
            - name: NEO4J_DATA_URL
              value: {{ .Values.neo4j.dataUrl }}
          volumeMounts:
            - mountPath: /data
              name: {{ include "robokopkg.fullname" . }}-neo4jkp-pvc
              subPath: neo4j_data
            - name: {{ include "robokopkg.fullname" . }}-scripts
              mountPath: /download_data.sh
              subPath: download_data.sh
        - name: {{ include "robokopkg.fullname" . }}-neo4j-seed-container
          image: {{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag }}
          command:
            - '/seed_db.sh'
          volumeMounts:
            - mountPath: /data
              name: {{ include "robokopkg.fullname" . }}-neo4jkp-pvc
              subPath: neo4j_data
            - name: {{ include "robokopkg.fullname" . }}-scripts
              mountPath: /seed_db.sh
              subPath: seed_db.sh
      {{- end }}
      containers:
        - image: {{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag }}
          name: {{ include "robokopkg.fullname" . }}-neo4j-container
          imagePullPolicy:  {{ .Values.neo4j.image.imagePullPolicy }}
          env:
          - name: NEO4J_AUTH
          {{ if .Values.neo4j.password }}
            value: {{ .Values.neo4j.username }}/{{ .Values.neo4j.password }}
          {{ else }}
            value: "none"
          {{ end }}

          - name: NEO4J_browser_remote__content__hostname__whitelist
            {{ if .Values.nginx.service.hostName }}
            value: {{ .Values.nginx.service.hostName }}
            {{ else }}
            value: {{ .Values.nginx.service.loadBalancerIP }}
            {{ end }}
          - name: NEO4J_dbms_security_procedures_unrestricted
            value: "gds.*,apoc.*"
          - name: "NEO4J_dbms_security_procedures_whitelist"
            value: "gds.*,apoc.*"
          - name: NEO4J_dbms_connectors_default__listen__address
            value: "0.0.0.0"
          - name: "NEO4J_dbms_connector_bolt_listen__address"
            value: "0.0.0.0:7687"
          - name: NEO4J_dbms_memory_heap_initial__size
            value: "{{ .Values.neo4j.heapSize }}"
          - name: NEO4J_dbms_memory_heap_max__size
            value: "{{ .Values.neo4j.heapSize }}"
          - name: NEO4J_dbms_memory_pagecache_size
            value: "{{ .Values.neo4j.pageCacheSize }}"
          - name: NEO4J_dbms_read__only
            value: "{{ .Values.neo4j.readOnly }}"
          - name: NEO4J_dbms_jvm_additional
            value: "{{ .Values.neo4j.jvmOptions }}"
          - name: NEO4J_dbms_transaction_timeout
            value: "{{ .Values.neo4j.queryTimeout }}s"
          - name: NEO4J_dbms_default__advertised__address
            {{ if .Values.nginx.service.hostName }}
            value: {{ .Values.nginx.service.hostName }}
            {{ else }}
            value: {{ .Values.nginx.service.loadBalancerIP }}
            {{ end }}
          - name: NEO4J_dbms_connector_bolt_advertised__address
            {{ if .Values.nginx.service.hostName }}:{{ .Values.nginx.service.boltPort }}
            value: {{ .Values.nginx.service.hostName }}:{{ .Values.nginx.service.boltPort }}
            {{ else }}
            value: {{ .Values.nginx.service.loadBalancerIP }}:{{ .Values.nginx.service.boltPort }}
            {{ end }}
          ports:
            - name: neo4j-http
              containerPort: 7474
              protocol: TCP
            - name: neo4j-https
              containerPort: 7473
              protocol: TCP
            - name: neo4j-bolt
              containerPort: 7687
              protocol: TCP
          resources:
            requests:
              memory: {{ .Values.neo4j.totalMemory }}
            limits:
              cpu: 1
              memory: {{ .Values.neo4j.totalMemory }}

          volumeMounts:
          - mountPath: /data
            name: {{ include "robokopkg.fullname" . }}-neo4jkp-pvc
            subPath: neo4j_data
          - mountPath: /logs
            name: {{ include "robokopkg.fullname" . }}-neo4jkp-pvc
            subPath: neo4j_logs
          startupProbe:
{{ toYaml .Values.neo4j.startupProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.neo4j.readinessProbe | indent 12 }}
          livenessProbe:
{{ toYaml .Values.neo4j.livenessProbe | indent 12 }}
      restartPolicy: Always
    {{ with .Values.neo4j.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
    {{ end }}
    {{ with .Values.neo4j.tolerations }}
      tolerations:
      {{ toYaml . | nindent 8 }}
    {{ end }}
      volumes:
        - name: {{ include "robokopkg.fullname" . }}-scripts
          configMap:
            name: {{ include "robokopkg.fullname" . }}-configmap
            defaultMode: 0777
  volumeClaimTemplates:
    - metadata:
        name: {{ include "robokopkg.fullname" . }}-neo4jkp-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.neo4j.storage.size }}
