apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "robokopkg.fullname" . }}-nginx-configmap
data:
  nginx-http.conf: |-
    upstream webserver{
        server {{ include "robokopkg.fullname" . }}-guides-service:{{ .Values.guides.service.port }};
    }
    upstream neo4j{
     server {{ include "robokopkg.fullname" . }}-neo4j-service:7474;
    }

    server {
      listen 0.0.0.0:8080;
      location / {
       proxy_pass http://neo4j;
       proxy_set_header Host $host;
       proxy_set_header        X-Forwarded-Proto $scheme;
      }

      location /guide {
        proxy_pass http://webserver/guide;
        proxy_set_header        X-Forwarded-Proto $scheme;
      }

      location /guide/dumps {
       proxy_pass http://webserver/guide/dumps;
       proxy_set_header        X-Forwarded-Proto $scheme;
      }

      location /guide/learn {
        proxy_pass http://webserver/guide/learn;
        proxy_set_header        X-Forwarded-Proto $scheme;
      }

      location ^~ /static {
        proxy_pass http://webserver/static;
        proxy_set_header        X-Forwarded-Proto $scheme;
      }

      location ~ (\.(db)|\.(sql)|\.(rdb)) {
           root /dumps;
       }
    }

  nginx-default.conf: |-
    # Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
    user              www www;  ## Default: nobody

    worker_processes  auto;
    error_log         "/opt/bitnami/nginx/logs/error.log";
    pid               "/opt/bitnami/nginx/tmp/nginx.pid";

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        log_format    main '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status  $body_bytes_sent "$http_referer" '
                           '"$http_user_agent" "$http_x_forwarded_for"';
        access_log    "/opt/bitnami/nginx/logs/access.log";
        add_header    X-Frame-Options SAMEORIGIN;

        client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
        proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
        fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
        scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
        uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;

        sendfile           on;
        tcp_nopush         on;
        tcp_nodelay        off;
        gzip               on;
        gzip_http_version  1.0;
        gzip_comp_level    2;
        gzip_proxied       any;
        gzip_types         text/plain text/css application/javascript text/xml application/xml+rss;
        keepalive_timeout  65;
        ssl_protocols      TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers        HIGH:!aNULL:!MD5;
        client_max_body_size 80M;
        server_tokens off;


        include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";
    }
    stream {
       log_format basic '$remote_addr [$time_local] '
                 '$protocol $status $bytes_sent $bytes_received '
                 '$session_time';
        server {
            listen 0.0.0.0:7687;
            proxy_pass {{ include "robokopkg.fullname" . }}-neo4j-service:7687;
            }
    }