apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "robokopkg.fullname" . }}-nginx
  labels:
    {{- include "robokopkg.selectorLabels" . | nindent 4 }}
    app: nginx
spec:
  selector:
    matchLabels:
      {{- include "robokopkg.selectorLabels" . | nindent 6 }}
      app: nginx
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "robokopkg.selectorLabels" . | nindent 8 }}
        app: nginx
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "robokopkg.fullname" . }}-nginx-configmap
            defaultMode: 0777
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: bolt
              containerPort: 7687
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /guide
              port: http
          readinessProbe:
            httpGet:
              path: /guide
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: "/opt/bitnami/nginx/conf/server_blocks/default.conf"
            name: "nginx-config"
            subPath: "nginx-http.conf"
          - mountPath: "/opt/bitnami/nginx/conf/nginx.conf"
            name: "nginx-config"
            subPath: "nginx-default.conf"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
