{{- if .Values.backend.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "robokop-ui.fullname" .}}-explore-database-pvc
  labels:
    {{- include "robokop-ui.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: basic
{{- end }}
