apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "robokop-ui.fullname" . }}-frontend
  labels:
    {{- include "robokop-ui.labels" . | nindent 4 }}
    service-type: webserver
spec:
  selector:
    matchLabels:
      {{- include "robokop-ui.selectorLabels" . | nindent 6 }}
      service-type: webserver
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "robokop-ui.selectorLabels" . | nindent 8 }}
        service-type: webserver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-robokop-ui-frontend
          {{- with .Values.frontend.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
