apiVersion: v1
kind: Service
metadata:
  name: {{ include "robokop-ui.fullname" .}}-frontend-svc
  labels:
    {{- include "robokop-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "robokop-ui.selectorLabels" . | nindent 4 }}
    service-type: webserver
