apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "information-radiator.labels" . | nindent 4 }}
    service-type: redis
  name: {{ include "information-radiator.fullname" . }}-redis
spec:
  selector:
    matchLabels:
      {{- include "information-radiator.selectorLabels" . | nindent 6 }}
      service-type: redis
  template:
    metadata:
      labels:
        {{- include "information-radiator.selectorLabels" . | nindent 8 }}
        service-type: redis
    spec:
      containers:
        - name: {{ include "information-radiator.fullname" . }}-redis
          image: 'redis:{{ .Values.redis.tag }}'
          ports:
            - name: redis-port
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
          args:
            - --requirepass
            - {{ .Values.redis.password }}
          {{ if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{ end }}
      restartPolicy: Always
