dataUrl: https://stars.renci.org/var/plater/bl-4.2.1/CTKP_Automat/3a11bc62b676c6aa/neo4j.dump
metadataUrl: https://stars.renci.org/var/plater/bl-4.2.1/CTKP_Automat/3a11bc62b676c6aa/CTKP_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-4.2.1/CTKP_Automat/3a11bc62b676c6aa/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-4.2.1/CTKP_Automat/3a11bc62b676c6aa/testing_data.json