pipeline {
    options {
        timestamps()
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    agent {
        node { label 'translator && aws && build' }
    }
    parameters {
        string(name: 'BUILD_VERSION', defaultValue: '', description: 'The build version to deploy (optional)')
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region to deploy')
        string(name: 'KUBERNETES_CLUSTER_NAME', defaultValue: 'translator-eks-ci-blue-cluster', description: 'AWS EKS that will host this application')
    }
    triggers {
        pollSCM('H/2 * * * *')
    }
    environment {
        DEPLOY_ENV = "ci"
    }
    stages {
        stage('Clean') {
            steps {
                cleanWs()
                checkout scm
            }
        }
        stage('Build Version aragorn') {
            when {
                allOf {
                    expression {
                        return !params.BUILD_VERSION
                        return !params.BUILD_VERSION_MQ
                    }
                    anyOf {
                        changeset "helm/aragorn/*"
                        triggeredBy 'UserIdCause'
                    }
                }
            }
            steps{
                script {
                    script {
                        def imageMeta = readYaml file: 'helm/aragorn/ncats-images-meta.yaml'
                        env.ORIGINAL_REPO = imageMeta.aragorn.image
                        env.BUILD_VERSION = imageMeta.aragorn.version
                        env.ORIGINAL_REPO_MQ = imageMeta.aragornRabbitMq.image
                        env.BUILD_VERSION_MQ = imageMeta.aragornRabbitMq.version
                        currentBuild.displayName = imageMeta.aragorn.version + "#" + imageMeta.aragornRabbitMq.version
                    }
                }
            }
        }
        stage('Build aragorn') {
            when {
                allOf {
                    expression {
                        return !params.BUILD_VERSION
                    }
                    anyOf {
                        changeset "helm/aragorn/*"
                        triggeredBy 'UserIdCause'
                    }
                }
            }
            steps {
                withEnv([
                    "IMAGE_NAME=853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-aragorn",
                    "BUILD_VERSION=" +  (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[0] : env.BUILD_VERSION)
                ]) {
                    dir("helm/aragorn") {
                        script {
                            sh '''
                            docker pull $ORIGINAL_REPO:$BUILD_VERSION
                            docker tag $ORIGINAL_REPO:$BUILD_VERSION $IMAGE_NAME
                            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 853771734544.dkr.ecr.us-east-1.amazonaws.com
                            '''
                            docker.image(env.IMAGE_NAME).push("${BUILD_VERSION}")
                        }
                    }
                }
                withEnv([
                    "IMAGE_NAME=853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-aragorn-rabbitmq",
                    "BUILD_VERSION_MQ=" + (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[1] : env.BUILD_VERSION_MQ)
                ]) {
                    dir("helm/aragorn") {
                        script {
                            sh '''
                            docker pull $ORIGINAL_REPO_MQ:$BUILD_VERSION_MQ
                            docker tag $ORIGINAL_REPO_MQ:$BUILD_VERSION_MQ $IMAGE_NAME
                            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 853771734544.dkr.ecr.us-east-1.amazonaws.com
                            '''
                            docker.image(env.IMAGE_NAME).push("${BUILD_VERSION_MQ}")
                        }
                    }
                }
            }
        } 
        stage('Deploy') {
            agent {
                label 'translator && ci && deploy'
            }
            when {
                anyOf {
                    changeset "helm/strider/*"
                    triggeredBy 'UserIdCause'
                }
            }
            environment {
              APP = "aragorn"
            }
            steps {
                checkout scm
                dir("helm/aragorn") {
                    configFileProvider([
                        configFile(fileId: 'prepare.sh', targetLocation: 'prepare.sh')
                    ]){    
                        withEnv([
                            "BUILD_VERSION_ARAGORN=" + (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[0] : env.BUILD_VERSION),
                            "BUILD_VERSION_MQ=" + (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[1] : env.BUILD_VERSION_MQ)
                        ]) {
                            sh '''
                            /bin/bash prepare.sh
                            mv ncats-dev-values.yaml ./values-ncats.yaml
                            /bin/bash deploy.sh
                            '''
                        }
                    }
                }
            }
            post {
                always {
                    echo " Clean up the workspace in deploy node!"
                    cleanWs()
                }
            }
        }
    }
}