dataUrl: https://stars.renci.org/var/plater/bl-4.1.6/CAMKP_Automat/9ccf224361f0ba8a/graph_9ccf224361f0ba8a.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-4.1.6/CAMKP_Automat/9ccf224361f0ba8a/CAMKP_Automat.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-4.1.6/CAMKP_Automat/9ccf224361f0ba8a/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-4.1.6/CAMKP_Automat/9ccf224361f0ba8a/testing_data.json