dataUrl: https://stars.renci.org/var/plater/bl-4.1.6/icees-kg/1.4.4/graph.db.dump
metadataUrl: https://stars.renci.org/var/plater/bl-4.1.6/icees-kg/1.4.4/icees-kg.meta.json
metaKGUrl: https://stars.renci.org/var/plater/bl-4.1.6/icees-kg/1.4.4/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/bl-4.1.6/icees-kg/1.4.4/testing_data.json
