nameLookup:
  image: ghcr.io/ncatstranslator/nameresolution
  version: v1.5.2

solr:
  image: solr
  version: "9.1"

renciPythonImage:
  image: ghcr.io/translatorsri/renci-python-image
  version: latest
