{{- if .Values.ingress.enabled -}}
{{- $fullName := include "aragorn-ranker.fullname" . -}}

{{- $svcPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "aragorn-ranker.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/1.2(/|$)(.*)"
            backend:
              serviceName: {{ $fullName }}-web-trapi-1-2
              servicePort: {{ $svcPort }}
{{- end }}
