{{- if .Values.kpRegistry.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "strider.fullname" . }}-kp-registry
  labels:
    {{- include "strider.labels" . | nindent 4 }}
    service-type: database
spec:
  serviceName: {{ include "strider.fullname" . }}-kp-registry
  selector:
    matchLabels:
      {{- include "strider.selectorLabels" . | nindent 6 }}
      service-type: database
  template:
    metadata:
      labels:
        {{- include "strider.selectorLabels" . | nindent 8 }}
        service-type: database
    spec:
      containers:
        - name: {{ .Chart.Name }}-kp-registry-container
          image: "{{ .Values.kpRegistry.image.repository }}:{{ .Values.kpRegistry.image.tag }}"
          env:
            {{ if .Values.HTTPS_PROXY }}
            - name: "HTTPS_PROXY"
              value: "{{ .Values.HTTPS_PROXY }}"
            {{ end }}
            {{ if .Values.NO_PROXY }}
            - name: "NO_PROXY"
              value: "{{ .Values.NO_PROXY}}"
            {{ end }}
            - name: "OPENAPI_SERVER_MATURITY"
              value: "{{ .Values.x_trapi.maturity.value }}"
            - name: "OPENAPI_SERVER_LOCATION"
              value: "{{ .Values.x_trapi.location.value }}"
            - name: OPENAPI_SERVER_URL
              value: https://{{ .Values.ingress.kpRegistry.host }}
          ports:
            - name: http
              containerPort: {{ .Values.kpRegistry.containerPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.kpRegistry.dbPath }}
              name: {{ include "strider.fullname" . }}-kp-registry-data-volume
              subPath: data
          resources:
            {{ toYaml .Values.kpRegistry.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.kpRegistry.path }}
              port: http
            failureThreshold: {{ .Values.probes.kpRegistry.failureThreshold }}
            periodSeconds: {{ .Values.probes.kpRegistry.period }}
            successThreshold: {{ .Values.probes.kpRegistry.successThreshold }}

  volumeClaimTemplates:
    - metadata:
        name: {{ include "strider.fullname" . }}-kp-registry-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  {{- end }}