pipeline {
    options {
        timestamps()
        skipDefaultCheckout()
        disableConcurrentBuilds()
    }
    agent {
        node { label 'translator && aws && build' }
    }
    parameters {
        string(name: 'BUILD_VERSION', defaultValue: '', description: 'The build version to deploy (optional)')
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS Region to deploy')
        string(name: 'KUBERNETES_CLUSTER_NAME', defaultValue: 'translator-eks-ci-blue-cluster', description: 'AWS EKS that will host this application')
    }
    triggers {
        pollSCM('H/2 * * * *')
    }
    stages {
        stage('Clean') {
            steps {
                cleanWs()
                checkout scm
            }
        }
        stage('Build Version - strider') {
            when {
                allOf {
                    expression {
                        return !params.BUILD_VERSION
                        return !params.BUILD_VERSION_KP
                    }
                    anyOf {
                        changeset "helm/strider/*"
                        triggeredBy 'UserIdCause'
                    }
                }
            }
            steps{
                script {
                    script {
                        def imageMeta = readYaml file: 'helm/strider/ncats-images-meta.yaml'
                        env.ORIGINAL_REPO = imageMeta.strider.image
                        env.BUILD_VERSION = imageMeta.strider.version
                        env.ORIGINAL_REPO_KP = imageMeta.kpRegistry.image
                        env.BUILD_VERSION_KP = imageMeta.kpRegistry.version
                        currentBuild.displayName = imageMeta.strider.version + "#" + imageMeta.kpRegistry.version
                    }
                }
            }
        }
        stage('build - strider') {
            when {
                allOf {
                    expression {
                        return !params.BUILD_VERSION
                    }
                    anyOf {
                        changeset "helm/strider/*"
                        triggeredBy 'UserIdCause'
                    }
                }
            }
            steps {
                withEnv([
                    "IMAGE_NAME=translator-strider",
                    "BUILD_VERSION=" + (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[0] : env.BUILD_VERSION)
                ]) {
                    dir("helm/strider") {
                        script {

                            sh '''
                            docker pull $ORIGINAL_REPO:$BUILD_VERSION
                            docker tag $ORIGINAL_REPO:$BUILD_VERSION 853771734544.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$BUILD_VERSION
                            '''
                            def image = docker.image("853771734544.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$BUILD_VERSION")
                            docker.withRegistry('https://853771734544.dkr.ecr.us-east-1.amazonaws.com', 'ecr:us-east-1:aws-ifx-deploy') {
                                image.push()
                            }
                        }
                    }
                }
                withEnv([
                    "IMAGE_NAME=translator-kp-registry",
                    "BUILD_VERSION_KP=" + (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[1] : env.BUILD_VERSION_KP)
                ]) {
                    dir("helm/strider") {
                        script {

                            sh '''
                            docker pull $ORIGINAL_REPO_KP:$BUILD_VERSION_KP
                            docker tag $ORIGINAL_REPO_KP:$BUILD_VERSION_KP 853771734544.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$BUILD_VERSION_KP
                            '''
                            def image = docker.image("853771734544.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$BUILD_VERSION_KP")
                            docker.withRegistry('https://853771734544.dkr.ecr.us-east-1.amazonaws.com', 'ecr:us-east-1:aws-ifx-deploy') {
                                image.push()
                            }
                        }
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                anyOf {
                    changeset "helm/strider/*"
                    triggeredBy 'UserIdCause'
                }
            }
            steps {
                withCredentials(bindings:[sshUserPrivateKey(
                    credentialsId: 'labshare-svc',
                    keyFileVariable: 'PASSWORD')]) 
                {
                    configFileProvider([
                        configFile(fileId: 'values-ci.yaml', targetLocation: 'values-ncats.yaml')
                    ]){
                        withCredentials([
                            file(
                                credentialsId: 'sri-git-crypt.key.asc',
                                variable: 'cryptasc'),
                            file(
                                credentialsId: 'sri-git-crypt.key.pwd',
                                variable: 'cryptpwd'),   
                        ]){
                            withEnv([
                                "BUILD_VERSION_STRIDER=" + (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[0] : env.BUILD_VERSION),
                                "BUILD_VERSION_KP=" + (params.BUILD_VERSION ? params.BUILD_VERSION.tokenize("#")[1] : env.BUILD_VERSION_KP)
                            ]) {
                                withAWS(credentials:'aws-ifx-deploy') {
                                    sh '''
                                    # copy secret files to current directory
                                    cp $cryptasc sri-git-crypt.key.asc
                                    cp $cryptpwd sri-git-crypt.key.pwd
                                    # git crypt unlock the repo
                                    gpg --pinentry-mode=loopback --passphrase-file sri-git-crypt.key.pwd --decrypt sri-git-crypt.key.asc | git-crypt unlock -
                                    cd helm/strider
                                    cp $$PASSWORD password
                                    git clone https://labshare-svc:$password@github.com/Sphinx-Automation/translator-ops.git
                                    aws --region ${AWS_REGION} eks update-kubeconfig --name ${KUBERNETES_CLUSTER_NAME}
                                    cp -R translator-ops/ops/sri/strider/deploy/* ./
                                    mv ../../values-ncats.yaml ./jenkins-values-ncats.yaml
                                    mv ncats-dev-values.yaml ./values-ncats.yaml
                                    /bin/bash deploy.sh
                                    '''
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
