apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "r3.fullname" . }}-configmap
  labels:
    {{- include "r3.labels" . | nindent 4 }}
data:
  seed_db.sh: |-
    #!/bin/sh
    set -x
    FILE=/data/dump.rdb
    wget -O $FILE {{ .Values.data_url }}
  ping_redis.sh: |-
    #!/bin/bash
    set -x
    resp=$(redis-cli -h $REDIS_HOST -p $REDIS_PORT PING)
    until [ "$resp" = "PONG" ]; do
      resp=$(redis-cli -h $REDIS_HOST -p $REDIS_PORT PING)
      echo "No valid resp from redis sleeping... "
      sleep 2
    done
    echo "redis is live."
