apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "r3.fullname" . }}-root-webserver
  labels:
    {{- include "r3.labels" . | nindent 4 }}
    main-path: "root"
    service-type: webserver
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "r3.selectorLabels" . | nindent 6 }}
      main-path: "root"
      service-type: webserver
  template:
    metadata:
      labels:
        {{- include "r3.selectorLabels" . | nindent 8 }}
        service-type: webserver
        main-path: "root"
    spec:
      initContainers:
        - name: {{ include "r3.fullname" . }}-web-init-container
          image:  {{ .Values.redisImage.repository }}:{{ .Values.redisImage.tag }}
          command:
            - /ping_redis.sh
          env:
            - name: REDIS_HOST
              value: "{{ include "r3.fullname" . }}-redis-service"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port}}"
          volumeMounts:
            - name: {{ include "r3.fullname" . }}-ping-script
              mountPath: /ping_redis.sh
              subPath: ping_redis.sh
      containers:
        - name: {{ .Chart.Name }}-webserver
          image: "{{ .Values.webserverImage.repository }}:{{ .Values.webserverImage.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.web.port }}
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: "{{ include "r3.fullname" . }}-redis-service"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port}}"
          livenessProbe:
            httpGet:
              path: /apidocs
              port: http
          readinessProbe:
            httpGet:
              path: /apidocs
              port: http
      volumes:
        - name: {{ include "r3.fullname" . }}-ping-script
          configMap:
            name: {{ include "r3.fullname" . }}-configmap
            defaultMode: 0777
