app:
  neo4j:
    dataUrl: https://stars.renci.org/var/data_services/translator_kg/2026_02_03/neo4j.dump 
  memgraph:
    dataUrl: https://stars.renci.org/var/data_services/translator_kg/2026_02_03/memgraph_output/memgraph_graph
graphMetadataUrl: https://stars.renci.org/var/data_services/translator_kg/2026_02_03/graph-metadata.json
schemaUrl: https://stars.renci.org/var/plater/graphs/RobokopKG/f10f782cda309e98/schema.json 
metadataUrl: https://stars.renci.org/var/data_services/translator_kg/2026_02_03/merge-metadata.json
metaKGUrl: https://stars.renci.org/var/plater/graphs/RobokopKG/f10f782cda309e98/meta_knowledge_graph.json
testingDataUrl: https://stars.renci.org/var/plater/graphs/RobokopKG/f10f782cda309e98/testing_data.json
