
{{- $protocol := include "server-protocol" .  -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "robokop-ara.fullname" . }}-env-configmap
data:
 {{- with (index .Values.ingress.hosts 0) }}
  OPENAPI_SERVER_URL: "{{ $protocol }}://{{ .host }}"
 {{- end }}
  OPENAPI_SERVER_MATURITY: {{ .Values.app.xTrapi.server.maturity | quote }}
  OPENAPI_SERVER_LOCATION: {{ .Values.app.xTrapi.server.location | quote }}
  PORT: {{ .Values.app.port | quote }}