apiVersion: v1
kind: Service
metadata:
  name: {{ include "robokop-ara.fullname" . }}-web-service-trapi-1-2
  labels:
    {{- include "robokop-ara.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "robokop-ara.selectorLabels" . | nindent 4 }}
