apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aragorn.fullname" . }}-queue-files-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.queue_files.storageSize }}