apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aragorn.fullname" . }}-trapi1-2
  labels:
    app: {{ include "aragorn.fullname" . }}
    trapi: "1.2"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aragorn.fullname" . }}
      trapi: "1.2"
  template:
    metadata:
      labels:
        app: {{ include "aragorn.fullname" . }}
        trapi: "1.2"
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 2000
        runAsGroup: 3000

      containers:
        - name: {{ .Chart.Name }}-web-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          envFrom:
            - configMapRef:
                name: {{ include "aragorn.fullname" . }}-configmap
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          command:
            - 'uvicorn'
          args:
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "{{ .Values.app.port }}"
            - "--workers"
            - "4"
            - "--root-path"
            - "/1.2"
            - "src.server:APP"
          volumeMounts:
            - name: aragorn-logs-vol
              mountPath: /repo/aragorn/logs
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      volumes:
        - name: aragorn-logs-vol
          persistentVolumeClaim:
            claimName: {{ include "aragorn.fullname" . }}-logs-pvc
