{{- if .Values.ingress.enabled -}}
{{- $fullName := include "aragorn.fullname" . -}}

{{- $svcPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "aragorn.labels" . | nindent 4 }}
  annotations:
    # TODO remove the class if deploying to sterling
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      keepalive_timeout {{ .Values.ingress.timeout }};
    nginx.ingress.kubernetes.io/connection-proxy-header: keep-alive
    nginx.ingress.kubernetes.io/send-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/service-upstream: 'true'
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "{{ .Values.ingress.timeout }}"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/1.2(/|$)(.*)"
            backend:
              serviceName: {{ include "aragorn.fullname" . }}-web-service-trapi-1-2
              servicePort: {{ $svcPort }}
{{- end }}
