{{- if .Values.ingress.enabled -}}
{{- $fullName := include "aragorn.fullname" . -}}

{{- $svcPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-trapi-1-1
  labels:
    {{- include "aragorn.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: "/1.1(/|$)(.*)"
            backend:
              serviceName: {{ include "aragorn.fullname" . }}-web-service-trapi-1-1
              servicePort: {{ $svcPort }}
{{- end }}
