apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aragorn.fullname" . }}-rbtmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rbtmq.storage.size }}

